name: Client and Server CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  client-test:
    name: Test React Client
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]  
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      
      - run: npm ci
        working-directory: ./client  

      - run: npm test
        working-directory: ./client  

  
  
  server-test:
    name: Test Node.js Server
    runs-on: ubuntu-latest
    needs: client-test

    strategy:
      matrix:
        node-version: [20.x]

    env:
      DB_USER: ${{ secrets.DB_USER }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_DATABASE: ${{ secrets.DB_DATABASE }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_PORT: ${{ secrets.DB_PORT }}
      FIREBASE_SERVICE_ACCOUNT_BASE64: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_BASE64 }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      
      - run: npm ci
        working-directory: ./server  

      - run: npm test
        working-directory: ./server/tests 

